# Generated by Django 3.2.8 on 2021-12-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='ADO',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ANH',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ANO',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Alkalinity',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='BOD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='COD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='DO',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='EBOD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ENH',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ETSS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Eph',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='FMLSS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='TSS',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ph',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='temp',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='watercons',
            field=models.IntegerField(max_length=10),
        ),
    ]
